# Generated by Django 5.2.17 on 2026-09-25 19:27

import food_reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=food_reports.models._report_image_upload_path, verbose_name='image'),
        ),
    ]
