# Generated by Django 5.2.17 on 2026-09-25 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        ('food_reports', '0002_alter_foodreport_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('REPORT_SUBMITTED', 'Report Submitted'), ('REPORT_STATUS_CHANGED', 'Report Status Changed'), ('AI_ANALYSIS_COMPLETED', 'AI Analysis Completed'), ('COMPLAINT_SUBMITTED', 'Complaint Submitted'), ('COMPLAINT_STATUS_CHANGED', 'Complaint Status Changed'), ('ESCALATION_CREATED', 'Escalation Created'), ('ESCALATION_UPDATED', 'Escalation Updated')], db_index=True, max_length=30, verbose_name='event type')),
                ('message', models.TextField(verbose_name='message')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='is read')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
                ('related_complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='complaints.complaint', verbose_name='related complaint')),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='food_reports.foodreport', verbose_name='related report')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notif_recipient_read_idx')],
            },
        ),
    ]
